spring:
  port: 8888
  profiles: dev
  datasource:
   url: jdbc:mysql://47.96.125.127:3306/salt?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/salt?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
   username: root
   password: qwe123
   driver-class-name: com.mysql.cj.jdbc.Driver
